USE `bank-server`;

CREATE TABLE `USERS` (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(100) NOT NULL,
    CURRENT_BALANCE DECIMAL(10,2) NOT NULL
);

CREATE TABLE `TRANSACTIONS` (
    ID INT NOT NULL AUTO_INCREMENT,
    TRANSACTION_AMOUNT DECIMAL(10,2) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TRANSACTION_TYPE ENUM('DEBIT', 'CREDIT') NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT `FK_USER_ID`
        FOREIGN KEY (USER_ID)
        REFERENCES `USERS` (ID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);